spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    enabled: false
server:
  port: 8085

